version: '2'
services:
  cacti:
    image: "clovett/cacti"
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - DB_NAME=cacti_master
      - DB_USER=cactiuser
      - DB_PASS=cactipassword
      - DB_HOST=db
      - DB_PORT=3306
      - DB_ROOT_PASS=rootpassword
      - INITIALIZE_DB=1
      - TZ=America/New_York
    volumes:
      - cacti-data:/cacti
      - cacti-backups:/backups
    links:
      - db
  db:
    image: "percona:5.7.14"
    restart: unless-stopped
    ports:
      - "3306:3306"
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=200
      - --max_heap_table_size=128M
      - --max_allowed_packet=32M
      - --tmp_table_size=128M
      - --join_buffer_size=128M
      - --innodb_buffer_pool_size=1G
      - --innodb_doublewrite=OFF
      - --innodb_flush_log_at_timeout=3
      - --innodb_read_io_threads=32
      - --innodb_write_io_threads=16
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - TZ=America/New_York
    volumes:
      - cacti-db:/var/lib/mysql
  smokeping:
    image: "linuxserver/smokeping"
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - TZ=America/New_York
    volumes:
      - smokeping-data:/data
      - smokeping-config:/config
  ntopng:
    image: mcncclovett/ntopng
    restart: unless-stopped
    network_mode: host
    command:
      - bash -c "redis-server /etc/redis.conf && ntopng --local-networks 10.0.0.0/8"
    volumes:
      - ntopng-config:/etc/ntopng
volumes:
  cacti-db:
  cacti-data:
  cacti-backups:
  smokeping-data:
  smokeping-config:
  ntopng-config:
  
